spring:
  application:
    name: financial-erp
  profiles:
    active: dev

  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    schemas: public
    locations: classpath:db/migration/public
    table: flyway_schema_history
    validate-on-migrate: true
    out-of-order: false
    create-schemas: false

app:
  set-password-url: /api/v1/auth/set-password
  security:
    jwt:
      access-token-expiry-seconds: 900
      refresh-token-expiry-seconds: 604800
      issuer: https://financial-erp.com
      token-type: Bearer

    invitation:
      expiry-seconds: 86400